// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVDMqZOecsb3M07G5WW6Ze1t_IFYxptmg',
    appId: '1:850391513480:web:510a5acf8111582936a23d',
    messagingSenderId: '850391513480',
    projectId: 'healtho-2ff65',
    authDomain: 'healtho-2ff65.firebaseapp.com',
    storageBucket: 'healtho-2ff65.appspot.com',
    measurementId: 'G-1CQJ2FJL0Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAE6h1qjLtwSkcprcLtO3h2sCIP_H3LWeA',
    appId: '1:850391513480:android:e302ec8833ba8bb036a23d',
    messagingSenderId: '850391513480',
    projectId: 'healtho-2ff65',
    storageBucket: 'healtho-2ff65.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDN9LfZlXc4V1DWbpt0rJp6AkvL_T3C3is',
    appId: '1:850391513480:ios:f7d348853b33de2036a23d',
    messagingSenderId: '850391513480',
    projectId: 'healtho-2ff65',
    storageBucket: 'healtho-2ff65.appspot.com',
    iosBundleId: 'com.example.healtho',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDN9LfZlXc4V1DWbpt0rJp6AkvL_T3C3is',
    appId: '1:850391513480:ios:f7d348853b33de2036a23d',
    messagingSenderId: '850391513480',
    projectId: 'healtho-2ff65',
    storageBucket: 'healtho-2ff65.appspot.com',
    iosBundleId: 'com.example.healtho',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVDMqZOecsb3M07G5WW6Ze1t_IFYxptmg',
    appId: '1:850391513480:web:4de94e609923d4fc36a23d',
    messagingSenderId: '850391513480',
    projectId: 'healtho-2ff65',
    authDomain: 'healtho-2ff65.firebaseapp.com',
    storageBucket: 'healtho-2ff65.appspot.com',
    measurementId: 'G-HE563CW417',
  );

}